parameters:
#    servinow_restaurant_drawer.example.class: Servinow\RestaurantDrawerBundle\Example

services:
#    servinow_restaurant_drawer.example:
#        class: %servinow_restaurant_drawer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
